const dictEiwa = {
    // 日本語（60個）
    "東京": { search: ["とうきょう", "トウキョウ", "tokyo"], html: "<p><b>英語:</b> Tokyo</p>" },
    "学校": { search: ["がっこう", "ガッコウ", "school"], html: "<p><b>英語:</b> school</p>" },
    "先生": { search: ["せんせい", "センセイ", "teacher"], html: "<p><b>英語:</b> teacher</p>" },
    "友達": { search: ["ともだち", "トモダチ", "friend"], html: "<p><b>英語:</b> friend</p>" },
    "家族": { search: ["かぞく", "カゾク", "family"], html: "<p><b>英語:</b> family</p>" },
    "勉強": { search: ["べんきょう", "ベンキョウ", "study"], html: "<p><b>英語:</b> study</p>" },
    "英語": { search: ["えいご", "エイゴ", "english"], html: "<p><b>英語:</b> English</p>" },
    "日本語": { search: ["nihorngo", "にほんご", "japanese"], html: "<p><b>英語:</b> Japanese</p>" },
    "本棚": { search: ["ほんだな", "ホンダナ", "bookshelf"], html: "<p><b>英語:</b> bookshelf</p>" },
    "教室": { search: ["きょうしつ", "キョウシツ", "classroom"], html: "<p><b>英語:</b> classroom</p>" },
    "時計": { search: ["とけい", "トケイ", "clock"], html: "<p><b>英語:</b> clock / watch</p>" },
    "電話": { search: ["でんわ", "デンワ", "phone"], html: "<p><b>英語:</b> phone</p>" },
    "電車": { search: ["でんしゃ", "デンシャ", "train"], html: "<p><b>英語:</b> train</p>" },
    "自転車": { search: ["じてんしゃ", "ジテンシャ", "bicycle"], html: "<p><b>英語:</b> bicycle</p>" },
    "車掌": { search: ["しゃしょう", "シャショウ", "conductor"], html: "<p><b>英語:</b> conductor</p>" },
    "駅員": { search: ["えきいん", "エキイン", "station"], html: "<p><b>英語:</b> station staff</p>" },
    "交番": { search: ["こうばん", "コウバン", "police"], html: "<p><b>英語:</b> police box</p>" },
    "病院": { search: ["びょういん", "ビョウイン", "hospital"], html: "<p><b>英語:</b> hospital</p>" },
    "薬局": { search: ["yaqyoku", "やっきょく", "pharmacy"], html: "<p><b>英語:</b> pharmacy</p>" },
    "公園": { search: ["こうえん", "コウエン", "park"], html: "<p><b>英語:</b> park</p>" },
    "動物園": { search: ["どうぶつえん", "ドウブツエン", "zoo"], html: "<p><b>英語:</b> zoo</p>" },
    "図書館": { search: ["としょかん", "トショカン", "library"], html: "<p><b>英語:</b> library</p>" },
    "映画館": { search: ["えいがかん", "エイガカン", "movie"], html: "<p><b>英語:</b> movie theater</p>" },
    "銀行": { search: ["ぎんこう", "ギンコウ", "bank"], html: "<p><b>英語:</b> bank</p>" },
    "郵便局": { search: ["ゆうびんきょく", "ユウビンキョク", "post"], html: "<p><b>英語:</b> post office</p>" },
    "商店街": { search: ["しょうてんがい", "ショウテンガイ", "shopping"], html: "<p><b>英語:</b> shopping street</p>" },
    "料理": { search: ["りょうり", "リョウリ", "cooking"], html: "<p><b>英語:</b> cooking</p>" },
    "食堂": { search: ["しょくどう", "ショクドウ", "cafeteria"], html: "<p><b>英語:</b> cafeteria</p>" },
    "朝御飯": { search: ["あさごはん", "アサゴハン", "breakfast"], html: "<p><b>英語:</b> breakfast</p>" },
    "昼御飯": { search: ["ひるごはん", "ヒルゴハン", "lunch"], html: "<p><b>英語:</b> lunch</p>" },
    "晩御飯": { search: ["ばんごはん", "バンゴハン", "dinner"], html: "<p><b>英語:</b> dinner</p>" },
    "お茶": { search: ["おちゃ", "オチャ", "tea"], html: "<p><b>英語:</b> tea</p>" },
    "水筒": { search: ["すいとう", "スイトウ", "water"], html: "<p><b>英語:</b> water bottle</p>" },
    "音楽": { search: ["おんがく", "オンガク", "music"], html: "<p><b>英語:</b> music</p>" },
    "楽器": { search: ["がっき", "ガッキ", "instrument"], html: "<p><b>英語:</b> musical instrument</p>" },
    "歌唱": { search: ["かしょう", "カショウ", "singing"], html: "<p><b>英語:</b> singing</p>" },
    "絵画": { search: ["かいが", "カイガ", "painting"], html: "<p><b>英語:</b> painting</p>" },
    "筆箱": { search: ["ふでばこ", "フデバコ", "pencil"], html: "<p><b>英語:</b> pencil case</p>" },
    "消しゴム": { search: ["けしごむ", "ケシゴム", "eraser"], html: "<p><b>英語:</b> eraser</p>" },
    "宿題": { search: ["しゅくだい", "シュクダイ", "homework"], html: "<p><b>英語:</b> homework</p>" },
    "試験": { search: ["しけん", "シケン", "test"], html: "<p><b>英語:</b> test</p>" },
    "運動": { search: ["うんどう", "ウンドウ", "exercise"], html: "<p><b>英語:</b> exercise</p>" },
    "野球": { search: ["やきゅう", "ヤキュウ", "baseball"], html: "<p><b>英語:</b> baseball</p>" },
    "庭球": { search: ["てにす", "テニス", "tennis"], html: "<p><b>英語:</b> tennis</p>" },
    "籠球": { search: ["ばすけ", "バスケ", "basketball"], html: "<p><b>英語:</b> basketball</p>" },
    "排球": { search: ["ばれー", "バレー", "volleyball"], html: "<p><b>英語:</b> volleyball</p>" },
    "蹴球": { search: ["さっかー", "サッカー", "soccer"], html: "<p><b>英語:</b> soccer</p>" },
    "水泳": { search: ["すいえい", "スイエイ", "swimming"], html: "<p><b>英語:</b> swimming</p>" },
    "階段": { search: ["かいだん", "カイダン", "stairs"], html: "<p><b>英語:</b> stairs</p>" },
    "窓口": { search: ["まどぐち", "マドグチ", "window"], html: "<p><b>英語:</b> window / counter</p>" },
    "切符": { search: ["きっぷ", "キップ", "ticket"], html: "<p><b>英語:</b> ticket</p>" },
    "改札": { search: ["かいさつ", "カイサツ", "gate"], html: "<p><b>英語:</b> ticket gate</p>" },
    "天気": { search: ["てんき", "テンキ", "weather"], html: "<p><b>英語:</b> weather</p>" },
    "太陽": { search: ["たいよう", "タイヨウ", "sun"], html: "<p><b>英語:</b> sun</p>" },
    "向日葵": { search: ["ひまわり", "ヒマワリ", "sunflower"], html: "<p><b>英語:</b> sunflower</p>" },
    "桜花": { search: ["おうか", "オウカ", "さくら"], html: "<p><b>英語:</b> cherry blossom</p>" },
    "紅葉": { search: ["もみじ", "モミジ", "こうよう"], html: "<p><b>英語:</b> autumn leaves</p>" },
    "富士山": { search: ["ふじさん", "フジサン", "fuji"], html: "<p><b>英語:</b> Mt. Fuji</p>" },
    "新幹線": { search: ["しんかんせん", "シンカンセン", "bullet"], html: "<p><b>英語:</b> bullet train</p>" },
    "お土産": { search: ["おみやげ", "オミヤゲ", "souvenir"], html: "<p><b>英語:</b> souvenir</p>" },

    // 英語（60個）★品詞を内蔵
    "Apple": { search: ["apple", "アップル", "りんご"], html: "<p><b>【名詞】</b> リンゴ</p>" },
    "Book": { search: ["book", "ブック", "ほん"], html: "<p><b>【名詞】</b> 本 ／ <b>【動詞】</b> 予約する</p>" },
    "Dog": { search: ["dog", "ドッグ", "いぬ"], html: "<p><b>【名詞】</b> 犬</p>" },
    "Cat": { search: ["cat", "キャット", "ねこ"], html: "<p><b>【名詞】</b> 猫</p>" },
    "Boy": { search: ["boy", "ボーイ", "おとこのこ"], html: "<p><b>【名詞】</b> 男の子、少年</p>" },
    "Girl": { search: ["girl", "ガール", "おんなのこ"], html: "<p><b>【名詞】</b> 女の子、少女</p>" },
    "Teacher": { search: ["teacher", "せんせい"], html: "<p><b>【名詞】</b> 先生、教師</p>" },
    "Student": { search: ["student", "がくせい"], html: "<p><b>【名詞】</b> 学生、生徒</p>" },
    "School": { search: ["school", "がっこう"], html: "<p><b>【名詞】</b> 学校</p>" },
    "Friend": { search: ["friend", "ともだち"], html: "<p><b>【名詞】</b> 友達、友人</p>" },
    "Family": { search: ["family", "かぞく"], html: "<p><b>【名詞】</b> 家族</p>" },
    "Home": { search: ["home", "おうち"], html: "<p><b>【名詞】</b> 自宅 ／ <b>【副詞】</b> 家に</p>" },
    "House": { search: ["house", "いえ"], html: "<p><b>【名詞】</b> 家、建物</p>" },
    "Room": { search: ["room", "へや"], html: "<p><b>【名詞】</b> 部屋</p>" },
    "Desk": { search: ["desk", "つくえ"], html: "<p><b>【名詞】</b> 机</p>" },
    "Chair": { search: ["chair", "いす"], html: "<p><b>【名詞】</b> 椅子</p>" },
    "Pen": { search: ["pen", "ペン"], html: "<p><b>【名詞】</b> ペン</p>" },
    "Pencil": { search: ["pencil", "えんぴつ"], html: "<p><b>【名詞】</b> 鉛筆</p>" },
    "Notebook": { search: ["notebook", "ノート"], html: "<p><b>【名詞】</b> ノート</p>" },
    "Clock": { search: ["clock", "とけい"], html: "<p><b>【名詞】</b> 時計（置き・壁掛け）</p>" },
    "Watch": { search: ["watch", "うでどけい"], html: "<p><b>【名詞】</b> 腕時計 ／ <b>【動詞】</b> 見る</p>" },
    "Bag": { search: ["bag", "かばん"], html: "<p><b>【名詞】</b> カバン、袋</p>" },
    "Shoes": { search: ["shoes", "くつ"], html: "<p><b>【名詞】</b> 靴</p>" },
    "Hat": { search: ["hat", "ぼうし"], html: "<p><b>【名詞】</b> 帽子（ふち有り）</p>" },
    "Shirt": { search: ["shirt", "シャツ"], html: "<p><b>【名詞】</b> シャツ</p>" },
    "Coat": { search: ["coat", "コート"], html: "<p><b>【名詞】</b> コート、上着</p>" },
    "Water": { search: ["water", "みず"], html: "<p><b>【名詞】</b> 水</p>" },
    "Milk": { search: ["milk", "ぎゅうにゅう"], html: "<p><b>【名詞】</b> 牛乳、ミルク</p>" },
    "Tea": { search: ["tea", "おちゃ"], html: "<p><b>【名詞】</b> お茶、紅茶</p>" },
    "Coffee": { search: ["coffee", "コーヒー"], html: "<p><b>【名詞】</b> コーヒー</p>" },
    "Rice": { search: ["rice", "ごはん"], html: "<p><b>【名詞】</b> 米、ご飯</p>" },
    "Bread": { search: ["bread", "パン"], html: "<p><b>【名詞】</b> パン</p>" },
    "Cake": { search: ["cake", "ケーキ"], html: "<p><b>【名詞】</b> ケーキ</p>" },
    "Egg": { search: ["egg", "たまご"], html: "<p><b>【名詞】</b> 卵</p>" },
    "Fish": { search: ["fish", "さかな"], html: "<p><b>【名詞】</b> 魚 ／ <b>【動詞】</b> 魚釣りをする</p>" },
    "Meat": { search: ["meat", "にく"], html: "<p><b>【名詞】</b> 肉</p>" },
    "Orange": { search: ["orange", "みかん"], html: "<p><b>【名詞】</b> オレンジ ／ <b>【形容詞】</b> 橙色の</p>" },
    "Banana": { search: ["banana", "バナナ"], html: "<p><b>【名詞】</b> バナナ</p>" },
    "Sun": { search: ["sun", "たいよう"], html: "<p><b>【名詞】</b> 太陽</p>" },
    "Moon": { search: ["moon", "つき"], html: "<p><b>【名詞】</b> 月</p>" },
    "Star": { search: ["star", "ほし"], html: "<p><b>【名詞】</b> 星</p>" },
    "Sky": { search: ["sky", "そら"], html: "<p><b>【名詞】</b> 空</p>" },
    "Rain": { search: ["rain", "あめ"], html: "<p><b>【名詞】</b> 雨 ／ <b>【動詞】</b> 雨が降る</p>" },
    "Snow": { search: ["snow", "ゆき"], html: "<p><b>【名詞】</b> 雪 ／ <b>【動詞】</b> 雪が降る</p>" },
    "Wind": { search: ["wind", "かぜ"], html: "<p><b>【名詞】</b> 風</p>" },
    "Sea": { search: ["sea", "うみ"], html: "<p><b>【名詞】</b> 海</p>" },
    "River": { search: ["river", "かわ"], html: "<p><b>【名詞】</b> 川</p>" },
    "Mountain": { search: ["mountain", "やま"], html: "<p><b>【名詞】</b> 山</p>" },
    "Tree": { search: ["tree", "き"], html: "<p><b>【名詞】</b> 木、樹木</p>" },
    "Flower": { search: ["flower", "はな"], html: "<p><b>【名詞】</b> 花</p>" },
    "Bird": { search: ["bird", "とり"], html: "<p><b>【名詞】</b> 鳥</p>" },
    "Car": { search: ["car", "くるま"], html: "<p><b>【名詞】</b> 車、自動車</p>" },
    "Train": { search: ["train", "でんしゃ"], html: "<p><b>【名詞】</b> 電車、列車 ／ <b>【動詞】</b> 訓練する</p>" },
    "Bike": { search: ["bike", "じてんしゃ"], html: "<p><b>【名詞】</b> 自転車、バイク</p>" },
    "Bus": { search: ["bus", "バス"], html: "<p><b>【名詞】</b> バス</p>" },
    "Plane": { search: ["plane", "ひこうき"], html: "<p><b>【名詞】</b> 飛行機</p>" },
    "Station": { search: ["station", "えき"], html: "<p><b>【名詞】</b> 駅</p>" },
    "Park": { search: ["park", "こうえん"], html: "<p><b>【名詞】</b> 公園 ／ <b>【動詞】</b> 駐車する</p>" },
    "Good": { search: ["good", "いい"], html: "<p><b>【形容詞】</b> 良い、上手な</p>" },
    "Happy": { search: ["happy", "うれしい"], html: "<p><b>【形容詞】</b> 幸せな、嬉しい</p>" }
};